CREATE TABLE PRODUCT (
    id BIGINT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    category VARCHAR(50) NOT NULL
);

CREATE TABLE PURCHASE_ORDER_PRODUCT (
    id BIGINT PRIMARY KEY,
    purchase_order_id BIGINT,
    product_id BIGINT,
    FOREIGN KEY (product_id) REFERENCES PRODUCT(id)
);
